### PR TITLE
update M2 hands-on  complete

### PR DESCRIPTION
**Pull request by jack89roberts**
Updated M2 hands-on files and merge develop to guidance.

@lannelin Maybe easier to review and merge this one, I'll close #91

### CODE REVIEW

**Review by lannelin — COMMENTED** [review]
Looks great. Thanks for your work on this.

I've hidden a couple of cells in jupyterlab.

Unfortunately, `guidance` is a bit out of date and we'll end up  with an extra copy of the hands-on notebooks with different names in current merge state :(
`hands-on.ipynb` and `2-hands-on.ipynb` (same for complete)

I'm not sure the best course of action. Do we want to take the plunge of remerging `develop` into `guidance` now? It's not the cleanest merge

**Comment by lannelin** [comment]
I now realise that I didn't do the equivalent hiding cells in the version that's in the `develop` branch :(

**Comment by lannelin** [comment]
Actually, the merge isn't too bad. I'll push it

**Comment by jack89roberts** [comment]
Thanks! If merging `develop` into `guidance` double-check you don't accidentally overwrite any complete hands-on files from the other modules (I think the convention from the others has been to use the same file, not have a separate `-complete` file)

**Comment by lannelin** [comment]
> Thanks! If merging develop into guidance double-check you don't accidentally overwrite any complete hands-on files from the other modules (I think the convention from the others has been to use the same file, not have a separate -complete file)

I think we're good to merge. The only changed hands-on files are from m3 and m4 but those weren't complete previously.

**Pull request merged**
