### PR TITLE
Replace md ipynb

### PR DESCRIPTION
**Pull request by AoifeHughes**
This replaced all the md files in m2 with ipynb native files.

### CODE REVIEW

**Comment by AoifeHughes** [comment]
- [x] I still need to proof this and check everything hasn't broken

**Comment by AoifeHughes** [comment]
*I* think this is fine, it's quite a substantial change though. Could someone else handle this in case I'm way off?

**Comment by callummole** [comment]
Great! Do you mind making _everything_ as a notebook? (i.e. even the markdown files that do not have code). This will make it easier to make a slides companion to each module.

**Comment by AoifeHughes** [comment]
✨ Fantastic idea ✨
On it now!

**Comment by AoifeHughes** [comment]
@callummole Commit https://github.com/alan-turing-institute/rds-course/pull/123/commits/4ec5c2b37d65ee03bfd8a629e8198c4210cfe645 does this.

**Comment by AoifeHughes** [comment]
*probably*

**Comment by callummole** [comment]
On a local build and (cursory) look through this all seems great.

**Pull request merged**
